name: Deploy to Github Pages

on: [push]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages
        run: npx ajv-cli validate -s usecases-info.schema.json -d usecases-info.json
